### PR TITLE
Convert to nuxtron

### PR DESCRIPTION
**Pull request by mook-as**
[rancher/dashboard](https://github.com/rancher/dashboard) uses Nuxt as a basis; in order to pull in more components, we'll need to do the same.  The landscape of electron-things there isn't as great, though, so here's a PR to use nuxtron, which appears to be the best non-obsolete thing in use (also using electron-builder).

Startup time is similar: about ~12 seconds for me from `npm run dev` to the Welcome window being visible.

I'm not sure if I'm doing all the linting necessary at this point.

I also need the PR to check if `npm run build` is doing the dumb thing and attempting to publish — but only under GitHub Actions.

### CODE REVIEW

**Review by ericpromislow — CHANGES_REQUESTED** [review]
The code changes look ok, but I rebased `60b-fix-module-resolver` against this branch to check for future problems, and found these:

```
$ npm run lint-nofix

error: '$nuxt' is not defined (no-undef) at src/components/Nav.vue:17:15:
…
error: '$nuxt' is not defined (no-undef) at src/components/Nav.vue:30:22:
```

I don't get that error when I run `npm run dev` . Looks like it has something to do with the workings of `node_modules/@nuxt/vue-app`

**Comment by ericpromislow** [comment]
This created a new populated folder at `ROOT/src/node_modules/.cache/nuxt` -- should this be `.gitignore`'d or committed? Or should the cache go in `ROOT/node_modules/.cache` along with `babel-loader`?

**Comment by mook-as** [comment]
All of `src/node_modules/` should already be `.gitignore`d; ~I'll double check~ Local config problem, I'll put it into the checked-in `.gitignore`.

Looking into the issue with the linter.

**Comment by ericpromislow** [comment]
The `ROOT/app` dir also gets created.

**Comment by mook-as** [comment]
It might not make sense to merge #93 (`60b-fix-module-resolver`) with this, because that's [already done](https://github.com/mattfarina/rd/pull/92/files#diff-9b3dbaa02c0e8787f5e1d14f7656a9e881826e64930406ae0ba16391fa8804f7R23) in this branch.

`vue-cli-service` wouldn't know about the Nuxt stuff, so using it to lint wouldn't make sense?  I'll make a follow-up to get better linting in place, but this PR seems large enough already.

**Comment by ericpromislow** [comment]
I'm fine obsoleting PR #93 if this PR does the job.

**Comment by ericpromislow** [comment]
This linter doesn't look at the .vue files.

**Comment by mook-as** [comment]
Pulled in the necessarily ESLint plugins to look at `*.vue` (at least when run via `npm run lint`); since this actually found things the `v-html` thing, it's correctly scanning the templates too.

Note that I've marked all the currently failing lints to `warn`, so that we can land this before we make changes to the rest of the code to whittle down the issues (and flipping them back to errors).

**Comment by mook-as** [comment]
Rebased to resolve conflict with #95, still needs a review.

**Comment by ericpromislow** [comment]
My mistake on the lint probem with `$nuxt` -- the vue-linter can't find it, but eslint didn't complain.

However your branch doesn't process the .vue files -- I added syntax errors to the script part, and didn't get anything.

*But* there's a problem with shutdown. When I use the tray menuitem to quit I get this message:
`2: Child exited with code undefined`

and the shell doesn't return.

```
$ ps auxww | grep -i nuxt
ericp            73035   0.0  2.3  4990612 383272 s009  S+   10:04AM   0:24.07 node /Users/ericp/workspace/rancher/desktop/node_modules/.bin/nuxt -p 8888 src
ericp            73034   0.0  0.5  4708640  85304 s009  S+   10:04AM   0:04.91 node /Users/ericp/workspace/rancher/desktop/node_modules/nuxtron/bin/nuxtron-dev
ericp            73033   0.0  0.1  4575504  23844 s009  S+   10:04AM   0:00.08 node /Users/ericp/workspace/rancher/desktop/node_modules/.bin/nuxtron dev
```

**Comment by mook-as** [comment]
As of 8e7ff5145bc19b34606d4873755455a80e4c19e8 it should lint `*.vue`; for example, it's showing warnings about `v-html` being used (which is a Vue template thing).

It appears that this doesn't shut down automatically on quitting the electron app; you'll need to `^C` to quit (because nuxtron doesn't kill the nuxt server).  On the up side, this means that factory reset works :D

**Comment by ericpromislow** [comment]
I blew away the old mook branch and linting is working fine.

Is it me, or did we never highlight the selected tab in the left panel of the Preferences window?

So calling `app.quit()` doesn't bring down the nuxt server?  I wanted to try by pressing the Factory Reset
button but it's disabled. Should it be?

**Comment by mook-as** [comment]
When running `npm run dev`, `app.quit` quits the electron app (main process), but not the development web server.  When packaged, that development web server doesn't exist (because it's packaged to static files).

I'll look into the tab selection thing.

**Comment by ericpromislow** [comment]
Looks good. Could you write up a separate issue to deal with the eslint issues:
- non-interpolating strings: all single-quotes, double-quotes, or don't care?
- missing semicolons
- I don't get the "missing trailing comma" message -- does json now allow them?
- indentation
- spacing around braces
- extra `=` for all comparisons. Should be on because js type promotion can have unexpected results

Most of the other warnings I agree with.

**Review by ericpromislow — APPROVED** [review]

**Pull request merged**
