### PR TITLE
Show error status to the user

### LINKED ISSUE #32: Turn rancher logo and status red on error
When kubernetes goes into an error state the status indicator on the tray drop down and the rancher logo should turn red. This will indicate an error.

We should be able to tie this into the events for status.

### PR DESCRIPTION
**Pull request by mook-as**
This closes #32: on error, the tray icon and the rancher logo in the header both turn red.

I'm not sure about that second part — that seems kind of ugly; we probably want a better design here.

To test:
1. Start minikube using version 1.19.3.
2. Quit rancher desktop.
3. Edit `~/Library/Preferences/rancher-desktop/settings.json` and change the version to 1.17.0
4. Restart rd

This triggers an error on startup as minikube will refuse to downgrade.

### CODE REVIEW

**Review by mattfarina — CHANGES_REQUESTED** [review]
I was thinking of something a little different.

Screen Shot 2021-01-06 at 1 58 23 PM

In the preferences window I didn't imagine the logo would be a different color. Looking at it there, I'm not sure I like it. Can we undo that or is there a reason to do it?

Screen Shot 2021-01-06 at 1 58 33 PM

In the drop down menu where the Kubernetes status is displayed with the logo can we have a red dot or red logo (if the logo licensing use allows for it). This is what I was looking for instead of the logo on the preferences window.

**Comment by ericpromislow** [comment]
Code LGTM, shouldn't be too much of a change to color the menu icon differently

**Comment by mook-as** [comment]
Changed to make the kubernetes icon in the menu red too, instead of the big rancher logo in the header.  That's _much_ better; I only did the header because I thought that was what #32 requested.

image

**Review by mattfarina — CHANGES_REQUESTED** [review]
Unfortunately, we need to use a red dot instead of a red Kubernetes logo. Per the [trademark ](https://www.linuxfoundation.org/trademark-usage/)usage document...

> A logo should not be displayed with color variations, or with other elements superimposed on top of the logo.

[Red is not one of the provided colors](https://github.com/cncf/artwork/tree/master/projects/kubernetes). The existing logos we use are directly from the provided logos.

**Comment by mook-as** [comment]
Changed to use icon from [octicons](https://github.com/primer/octicons/blob/master/icons/issue-opened-16.svg), which is MIT licensed:
image

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
